name: Daily maintenance (full refresh → snapshot → purge)

on:
  schedule:
    # KST 00:05 ≒ UTC 15:05
    - cron: '5 15 * * *'
  workflow_dispatch:

jobs:
  daily:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    concurrency:
      group: daily-maintenance
      cancel-in-progress: false
    env:
      PROD_API_BASE: ${{ secrets.PROD_API_BASE }}
      CRON_SECRET: ${{ secrets.CRON_SECRET }}

    steps:
      - name: Full refresh (all channels)
        run: |
          set -euo pipefail
          curl -L -sS --fail-with-body --retry 3 --retry-all-errors --max-time 300 \
            -X POST "$PROD_API_BASE/api/cron/full-refresh?concurrency=3&batchDelayMs=0" \
            -H "content-type: application/json" \
            -H "x-cron-secret: $CRON_SECRET" \
            -d '{}' | tee full-refresh.json

      - name: Stats snapshot (daily baseline)
        run: |
          set -euo pipefail
          curl -L -sS --fail-with-body --retry 3 --retry-all-errors --max-time 180 \
            -X POST "$PROD_API_BASE/api/stats/snapshot" \
            -H "content-type: application/json" \
            -H "x-cron-secret: $CRON_SECRET" \
            -d '{}' | tee stats-snapshot.json

      - name: Refresh ranking materialization
        run: |
          set -euo pipefail
          curl -L -sS --fail-with-body --retry 3 --retry-all-errors --max-time 300 \
            -X POST "$PROD_API_BASE/api/stats/rankings" \
            -H "content-type: application/json" \
            -H "x-cron-secret: $CRON_SECRET" \
            -d '{}' | tee rankings-refresh.json

      - name: Purge old data (videos>120d, daily>30d)
        run: |
          set -euo pipefail
          # ttlHours는 운영정책에 맞춰 조절 가능(null이면 순수 120일 컷만 적용)
          curl -L -sS --fail-with-body --retry 3 --retry-all-errors --max-time 180 \
            -X POST "$PROD_API_BASE/api/cron/purge-old?ttlHours=24" \
            -H "content-type: application/json" \
            -H "x-cron-secret: $CRON_SECRET" \
            -d '{}' | tee purge-old.json

      - name: Summary
        if: always()
        run: |
          {
            echo "## ✅ Daily maintenance summary"
            echo ""
            echo "### Full refresh"
            echo ""
            cat full-refresh.json
            echo ""
            echo "### Stats snapshot"
            echo ""
            cat stats-snapshot.json
            echo ""
            echo "### Rankings refresh"
            echo ""
            cat rankings-refresh.json
            echo ""
            echo "### Purge old"
            echo ""
            cat purge-old.json
          } >> "$GITHUB_STEP_SUMMARY"
