name: Hourly recent sync (all or by creator)

on:
  schedule:
    # 매시 정각(UTC). 필요하면 5분 오프셋으로 바꿔도 됨: '5 * * * *'
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  hourly:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    concurrency:
      group: hourly-recent-batch
      cancel-in-progress: false
    env:
      PROD_API_BASE: ${{ secrets.PROD_API_BASE }}
      CRON_SECRET: ${{ secrets.CRON_SECRET }}

    steps:
      - name: Recent batch (all channels)
        run: |
          set -euo pipefail
          # 전체 채널 recent 일괄. 필요 시 쿼리 추가 가능: ?platform=youtube 등
          curl -sSf --retry 3 --retry-all-errors --max-time 300 \
            -X POST "$PROD_API_BASE/api/sync/recent-batch" \
            -H "content-type: application/json" \
            -H "x-cron-secret: $CRON_SECRET" \
            -d '{}' | tee recent-batch.json

      - name: Summary
        run: |
          {
            echo "## ⏱️ Hourly recent sync summary"
            echo ""
            cat recent-batch.json
          } >> "$GITHUB_STEP_SUMMARY"
