name: Hourly recent sync (all or by creator)

on:
  schedule:
    # 매시 정각(UTC). 필요하면 5분 오프셋으로 바꿔도 됨: '5 * * * *'
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  hourly:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    concurrency:
      group: hourly-recent-batch
      cancel-in-progress: false
    env:
      PROD_API_BASE: ${{ secrets.PROD_API_BASE }}
      CRON_SECRET: ${{ secrets.CRON_SECRET }}

    steps:
      - name: Recent batch (all channels)
        run: |
          set -euo pipefail
          # ---------------- [수정!] ----------------
          # -sSf 뒤에 -vL 옵션을 추가합니다.
          # -v: verbose. 모든 통신 과정을 자세히 보여줘!
          # -L: Location. 리디렉션이 있으면, 그 주소를 따라가 줘!
          # -------------------------------------------
          curl -vL -sSf --retry 3 --retry-all-errors --max-time 300 \
            -X POST "$PROD_API_BASE/api/sync/recent-batch" \
            -H "content-type: application/json" \
            -H "x-cron-secret: $CRON_SECRET" \
            -d '{}' | tee recent-batch.json

      - name: Summary
        run: |
          {
            echo "## ⏱️ Hourly recent sync summary";
            echo "";
            if command -v jq >/dev/null 2>&1; then
              jq . recent-batch.json;
            else
              cat recent-batch.json;
            fi
          } >> "$GITHUB_STEP_SUMMARY"
